### ISSUE TITLE
What data should we present in the dropdown?

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/pantheon-hud#2]
Here's the result of the omnibus API call: https://gist.github.com/danielbachhuber/7b77697ed7e5f758c256

Ideas:
- When the environment was last deployed.
- Infrastructure details (PHP version, memory available, # of containers, # of db servers, Redis available)
- Plan details (plan level, backups enabled)
- Username and password if the environment is locked.
- Stub Terminus / WP-CLI command for easy copy and paste.

**Comment by bmackinney** [comment]
- Last n commits, configurable
- commits available on lower environment, with link to deploys took for current if test or live.
- Sftp/git mode on dev/Multidev
- walkme snippet injected in footer
-  results from wp_launch_check

**Comment by danielbachhuber** [comment]
@bmackinney great suggestions - thanks!

> walkme snippet injected in footer

What is "walkme"?

> results from wp_launch_check

I don't know that we should call this on pageload, but maybe we can stash the results of the latest check in an option or something.

**Comment by bmackinney** [comment]
@danielbachhuber Walkme is a tool we use on the dashboard to direct users through specific tasks.

**Comment by kopepasah** [comment]
@danielbachhuber @ataylorme this issue is a bit stale and I would love some feedback on potential data that we could display in the dropdown now.

It's been about four years since this initial iteration, has anyone done research into what information seems most relevant to display in the menu bar?

Also, wondering if it makes sense to potentially display this information on the Dashboard as well... 🤔

**Comment by danielbachhuber** [comment]
> It's been about four years since this initial iteration, has anyone done research into what information seems most relevant to display in the menu bar?

I don't think so, no. I agree this would be a good first step though.

**Comment by danielbachhuber** [comment]
Closing this for now. We can always open new issues for new ideas!
