### ISSUE TITLE
Pantheon logo overlays and obstructs the WordPress admin page

### ISSUE THREAD

**Issue by twooten** [pantheon-systems/pantheon-hud#25]
This began when updating to version 0.1.3.

Only happening in Safari Version 10.0.1 (11602.2.14.0.7) as far as I know.

![image](https://user-images.githubusercontent.com/500366/42861341-2fa5ae34-8a8d-11e8-99e3-058f048bc7d6.png)

**Comment by danielbachhuber** [comment]
#23 is the culprit. In my case, the logo ends up like this:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/36432/42879270-e373dae2-8a44-11e8-86d5-8e0c4f3db91c.png">

I suspect the example you've shared has some admin CSS that's impacting `img` tags.

**Comment by danielbachhuber** [comment]
@twooten I've just tagged a v0.1.4 release for this.
