### ISSUE TITLE
Not showing the environment details when hovering

### ISSUE THREAD

**Issue by ruthiehallarsis** [pantheon-systems/pantheon-hud#28]
I spin up a fresh install of a wordpress running PHP 7.2 and followed the instructions here: https://pantheon.io/docs/environment-indicator/

When i enabled the plugin and cleared caches, only the environment name is showing in the wordpress toolbar and nothing happens when hovering over it. Please see https://monosnap.com/file/y9ANS1RDVa0nPCMzYXXDdlms7q3fCU

I have also tried downgrading the PHP version to 7.1, 7.0 and 5.6 but it didn't help at all. 

Another customer in chat(I'm from CSE), also experience the same but his site is a wp network site. https://downloads.intercomcdn.com/i/o/86093026/cbddfb5576ae30c6dca10f90/Dashboard-no-dropdown.png

**Comment by danielbachhuber** [comment]
Hi @ruthiehallarsis,

Thanks for the report! 

I believe the immediate problem is that this `get_environment_details()` call is erred:

https://github.com/pantheon-systems/pantheon-hud/blob/2f6644bd35ffd9bc0fbff437651e195c9ccbbff4/inc/class-api.php#L67

I _think_ this is because the upstream API has changed:

https://github.com/pantheon-systems/pantheon-hud/blob/2f6644bd35ffd9bc0fbff437651e195c9ccbbff4/inc/class-api.php#L10

I'll see if I can track down more details so we can get this fixed.

**Comment by danielbachhuber** [comment]
Hi @ruthiehallarsis,

Just to provide an update on this: I still haven't tracked down the necessary API details. I'll be able to pick this up again when I do.

**Comment by ruthiehallarsis** [comment]
Hi @danielbachhuber no worries!

**Comment by dan-arcmedia** [comment]
The API endpoint https://api.live.getpantheon.com:8443 is no longer available. 

The new API endpoint is https://dashboard.pantheon.io/api/ and by the looks of it returns a completely different structured JSON. I found that API endpoint by monitoring the console while I navigated the Pantheon Dashboard. I tried some basic tests but could not get anything working.

It looks like the only thing we can do is wait for an update.

**Comment by ataylorme** [comment]
> The API endpoint api.live.getpantheon.com:8443 is no longer available.
> The new API endpoint is dashboard.pantheon.io/api and by the looks of it returns completely different JSON.

`api.live.getpantheon.com` and `dashboard.pantheon.io/api` are both active. The dashboard API uses cookie authentication and won't be accessible from PHP.

`api.live.getpantheon.com` is accessible with `pantheon_curl`, which injects the necessary certificate to make the request. It must be used over port `8443`. `pantheon_curl` defaults to port `443`.

Requests from PHP should look like this:

```php
$api_url = 'https://api.live.getpantheon.com/sites/self/code-upstream-updates';
$api_response = pantheon_curl($api_url, null, 8443);
$data = json_decode($api_response['body']);
```

The `sites/self/state` endpoint was removed. @danielbachhuber do you know what kind of site data HUD was getting from that endpoint?

The data may be able at a different endpoint. Let's connect and I can show you the ones I've discovered that are accessible from PHP.

**Comment by danielbachhuber** [comment]
> The `sites/self/state` endpoint was removed. @danielbachhuber do you know what kind of site data HUD was getting from that endpoint?

See the various use of `get_site_data()`:

* https://github.com/pantheon-systems/pantheon-hud/blob/2f6644bd35ffd9bc0fbff437651e195c9ccbbff4/inc/class-api.php#L22
* https://github.com/pantheon-systems/pantheon-hud/blob/2f6644bd35ffd9bc0fbff437651e195c9ccbbff4/inc/class-api.php#L40
* https://github.com/pantheon-systems/pantheon-hud/blob/2f6644bd35ffd9bc0fbff437651e195c9ccbbff4/inc/class-api.php#L54
* https://github.com/pantheon-systems/pantheon-hud/blob/2f6644bd35ffd9bc0fbff437651e195c9ccbbff4/inc/class-api.php#L73-L85

> The data may be able at a different endpoint.

Are there any docs I can reference, or other ways of tracking this down?

> Let's connect and I can show you the ones I've discovered that are accessible from PHP.

I'm planning to work on this Friday morning but I could push to Monday if more convenient.

**Comment by ataylorme** [comment]
@danielbachhuber Friday morning works for me. Send me a calendar invite and we can do some pair programming.

There are limited docs but they are not public and not all the endpoints documented are available from PHP. I'll do some testing and gather a list of endpoints and bring it Friday.

**Comment by ataylorme** [comment]
PHP version is available in `$_ENV['php_version']`.

A lot of the other data looks like it is available from `https://api.live.getpantheon.com/sites/self/environments/{environment}/settings`. I was able to find `allow_read_slaves`, `appserver`, `dbserver`, and `plan_name`.

**Comment by ataylorme** [comment]
Custom URL data can be retrieved from `https://api.live.getpantheon.com/sites/self/environments/live/domains`.

**Comment by danielbachhuber** [comment]
Just fixed this up and hope to release it early next week. Thanks!
