### ISSUE TITLE
Usage of Backwards Implode

### ISSUE THREAD

**Issue by kopepasah** [pantheon-systems/pantheon-hud#48]
Currently working through #33 and noticed what seems to be a [backwards implode](https://github.com/pantheon-systems/pantheon-hud/blob/master/pantheon-hud.php#L37) (or at least an implode with an unnecessary string passed as a parameter).

While I believe the intention was to allow for files nested within directories, it is currently not utilized (and/or implemented incorrectly) and throws a PHPCS error.

**Comment by ataylorme** [comment]
Thanks for the report @kopepasah

**Comment by danielbachhuber** [comment]
This was fixed up in #52
