### ISSUE TITLE
Feature request - Button to Clear Pantheon Page Cache

### ISSUE THREAD

**Issue by bthuss-matter** [pantheon-systems/pantheon-hud#60]
It would be great if there was a link that would clear the pantheon page cache so I could do it quickly without having to go into the plugin settings page each time.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @bthuss-matter.

This feature request might make more sense in [Pantheon Advanced Page Cache](https://github.com/pantheon-systems/pantheon-advanced-page-cache). It already has an admin toolbar button for flushing the cache on a given page:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/36432/76710975-ffd71700-66c8-11ea-9860-c648895ea19f.png">

Would that be sufficient for your needs? If not, could you share more detail about why, how often, etc. you need to clear the entire cache?

**Comment by bthuss-matter** [comment]
That feature is handy, but as you mentioned I do often find myself needing to clear the whole cache myself,  particularly while in development. 

I've found that while the pantheon advanced page cache does a good job of updating itself when I make routine content edits on pages and posts....when I update my site's menus and change options and update content through custom ACF options menus and flexible content fields that those parts of the cache are not updated automatically when changes are made.

**Comment by danielbachhuber** [comment]
Cool, sounds good. I've filed an issue for it: https://github.com/pantheon-systems/pantheon-advanced-page-cache/issues/147

We'll need to have some internal discussion of whether it's a feature we want to promote so significantly though.
