### ISSUE TITLE
Live environment shows domains from dev when Pantheon HUD active

### ISSUE THREAD

**Issue by westonruter** [pantheon-systems/pantheon-hud#72]
We just did a rebuild of amp-wp.org. In doing so, we populated content on dev and then pushed the database to live, which isn't the normal workflow I know. The Pantheon HUD plugin was active on dev when we synced the database to live. On live, we then strangely saw that when the user was logged-in, most of the links on the page would were referencing the dev environment, for example:

```html
<link rel="canonical" href="https://dev-wordpress-amp.pantheonsite.io/ecosystem/themes/">
```

As opposed to the expected:

```html
<link rel="canonical" href="https://amp-wp.org/ecosystem/themes/">
```

We tried doing a `wp search-replace` command, flushing the cache, and doing `wp cache flush`. But nothing fixed the problem.

It appears that the dev environment somehow was cached when going live, and we couldn't reset it.

The only thing that fixed it was deactivating the Pantheon HUD plugin.

**Comment by danielbachhuber** [comment]
Hey Weston 👋 

> We tried doing a `wp search-replace` command, flushing the cache, and doing `wp cache flush`. But nothing fixed the problem.
> 
> It appears that the dev environment somehow was cached when going live, and we couldn't reset it.

This is so weird. Pantheon HUD doesn't touch `site_url` or `home` at all, so I'm not sure how `rel=canonical` would be impacted.

One thought is that maybe your environment variables were incorrect for some reason, and the data presented in Pantheon HUD was simply symptomatic of the underlying problem.

> The only thing that fixed it was deactivating the Pantheon HUD plugin.

Did the problem re-appear when you activated it again?

**Comment by westonruter** [comment]
Strangely enough, Pantheon HUD doesn't seem to be causing the problem now. I was sure it was before, however. Now, the issue doesn't happen if I deactivate Yoast while HUD is still active. Very strange. We're continuing to look into it. I'll re-open this if we find it is indeed a HUD problem.

**Comment by danielbachhuber** [comment]
👍

**Comment by westonruter** [comment]
Cause: I neglected to include `--all-tables` when I did the `search-replace` after syncing the DB from `dev` to `live`.

**Comment by danielbachhuber** [comment]
Glad you were able to figure it out!

And sorry you had to use `--all-tables` 😬 . I think changing `wp search-replace`'s default behavior has come up a few times in the past, but I was always hesitant about unexpectedly breaking some backwards compat.
